name: Nightly Acceptance
on:
  schedule:
    - cron: '0 5 * * *' # UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - run: go test -v ./vultr -timeout 180m
        id: test
        env:
          CI: ${{ secrets.CI }}
          TF_ACC: ${{ secrets.TF_ACC }}
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Mattermost Message
        if: always()
        run: |
          echo "{\"text\":\"Terraform Nightly Acceptance Job Status: ${{ steps.test.outcome }}\n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" > mattermost.json

      - uses: mattermost/action-mattermost-notify@master
        if: always()
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON: ${{ secrets.MATTERMOST_ICON }}
